server:
    port: 9090
spring:
    datasource:
        driverClassName: org.postgresql.Driver
        password: ${POSTGRES_PASSWORD}
        url: ${SPRING_DATASOURCE_URL}
        username: ${POSTGRES_USER}
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL10Dialect
                format_sql: true
    sql:
        init:
            mode: always
